#= require <rand>

miscGenerators =
    painting: -> # {{{1

    note: -> # {{{1

    book: -> # {{{1
        #This is probably my favorite name generator.
        str = choose([
            choose([
                'All about '
                'Of '
                'Everything you need to know about'
                'The definitive guide to'
                'A beginner\'s guide to'
                'How to deal with'
                'Dealing with'
                'Hanging out with'
                'Making friends with'
                'I fell in love with'
                'Falling in love with'
                'The shocking truth about'
                'They\'re serious :'
                'Here\'s a book about'
                'A conversation with'
                'Why we need more'
                'Nobody understands'
                'Who cares about'
                'A study on'
                'These are not my'
                'Say no to'
                'Getting away from'
                'Getting along with'
                'Avoiding'
                'Approaching'
                'Investigating'
                'Not worth it :'
                'Stay away from'
                'Never underestimate'
                'Anatomy of'
                'I hate'
                'I love'
                'Who hates'
                'Who loves'
                'They were'
                'Living with'
                'Cooking with'
                'Cooking for'
                randint(10, 200) + ' recipes for'
                'A few words on'
                'They know where you live :'
                'What I think about'
                'What you didn\'t know about'
                'The truth on'
                'What they don\'t show you about'
                'Hey look,'
                'Aw crap,'
                'Holy crap,'
                'Understanding'
                'Getting rid of'
                'Delicious'
                'They\'re okay :'
                'Licking'
                'Reasoning with'
                'You can\'t explain that :'
                'Drawing'
                'Choosing your'
                'Night of the'
                'Day of the'
                'Revenge of the'
                'The book of'
                'The big book of'
                'Those aren\'t my'
                'Hey everyone,'
                'The chorus of'
            ]) + ' ' + choose([
                'weird'
                'mutant'
                'normal'
                'serious'
                'elongated'
                'exploding'
                'obese'
                'skinny'
                'whiny'
                'stupid'
                'slimy'
                'creamy'
                'tiny'
                'small'
                'giant'
                'gigantic'
                'ancient'
                'tasty'
                'obnoxious'
                'invisible'
                'shiny'
                'boring'
                'confused'
                'lost'
                'lonely'
                'curly'
                'frilly'
                'friendly'
                'annoying'
                'space'
                'green'
                'orange'
                'purple'
                'mauve'
                'transparent'
                'stilted'
                'hairy'
                'bald'
                'ridiculous'
                'demanding'
                'imaginary'
                'awkward'
                'stubborn'
                'pretentious'
                'naughty'
                'nasty'
                'lazy'
                'fancy'
                'magic'
                'clumsy'
                'smelly'
                'bearded'
                'sleazy'
                'rabid'
                'translucent'
                'edible'
                'inedible'
                'foreign'
                'snotty'
                'mind-reading'
                'telepathic'
                'silent'
            ]) + ' ' + choose([
                'shrimps'
                'birds'
                'people'
                'friends'
                'relatives'
                'chappies'
                'whales'
                'deities'
                'cactii'
                'fungi'
                'shellfish'
                'alligators'
                'jellyfish'
                'crabs'
                'hoboes'
                'machines'
                'robots'
                'goats'
                'cyborgs'
                'ninjas'
                'fish'
                'mushrooms'
                'mammals'
                'reptiles'
                'amphibians'
                'cephalopods'
                'spiders'
                'fossils'
                'moustaches'
                'perverts'
                'mermaids'
                'squids'
                'lampreys'
                'seafood'
                'turtles'
                'unicorns'
                'barbarians'
                'vampires'
                'werewolves'
                'teenagers'
                'babies'
                'kids'
                'ladies'
                'superheroes'
                'roads'
                'hats'
                'insects'
                'centaurs'
            ])
            choose([
                'Tales of'
                'Chronicles of'
                'A history of'
                'The gates of'
                'Objective : '
                'Reaching for'
                'War for'
                'Battle for'
                choose([
                    'Money'
                    'A savior'
                    'A wizard'
                    'A warrior'
                    'A hero'
                    'A prince'
                    'A king'
                    'A princess'
                    'A queen'
                    'Cake'
                    'Booze'
                ]) + ' for'
                'The ruins of'
                'The prophet of'
                'Zealots on'
                'Mysteries of'
                'The temple of'
                'The vagrant from'
                'The nights of'
                'Conquerors from'
                'They came from'
                'The spaceships on'
                'The soldiers of'
                'The warrior from'
                'On the moons of'
                'Saving'
                'Glory for'
                'Rulers of'
                'Kings of'
                'Lords of'
                'Princes of'
            ]) + ' ' + choose([
                'G'
                'P'
                'S'
                'St'
                'Sh'
                'B'
                'F'
                'K'
                'Z'
                'Az'
                'Oz'
            ]) + choose([
                ''
                ''
                ''
                'r'
                'l'
            ]) + choose([
                'u'
                'o'
                'a'
                'e'
            ]) + choose([
                'r'
                'sh'
                'nd'
                'st'
                'sd'
                'kl'
                'kt'
                'pl'
                'fr'
                'ck'
                'sh'
                'ff'
                'gg'
                'l'
                'lig'
                'rag'
                'sha'
                'pta'
                'lir'
                'limd'
                'lim'
                'shim'
                'stel'
            ]) + choose([
                'i'
                'u'
                'o'
                'oo'
                'e'
                'ee'
                'y'
                'a'
            ]) + choose([
                'll'
                'th'
                'h'
                'k'
                'lm'
                'r'
                'g'
                'gh'
                'n'
                'm'
                'p'
                's'
                'rg'
                'lg'
            ])
            choose([
                choose([
                    'How to'
                    'Learning how to'
                    'Teaching yourself how to'
                ]) + ' ' + choose([
                    'knit'
                    'dance'
                    'swim'
                    'cook'
                    'play piano'
                    'program'
                    'be cool'
                    'be popular'
                    'be friendly'
                    'be nice'
                    'be smarter'
                    'stay fit'
                    'be succesful'
                    'make money'
                    'be funny'
                    'find a job'
                    'write books'
                    'make a website'
                    'play chess'
                    'do magic tricks'
                    'do yoga'
                    'be happy'
                ])
                choose([
                    'A beginner\'s guide to'
                    'All about'
                    'Everything you need to know about'
                    'The basics of'
                    'The secrets of'
                    'The definitive guide to'
                    'Advanced techniques for'
                ]) + ' ' + choose([
                    'knitting'
                    'dancing'
                    'swimming'
                    'cooking'
                    'playing piano'
                    'programming'
                    'being cool'
                    'being popular'
                    'being friendly'
                    'being nice'
                    'getting smarter'
                    'staying fit'
                    'being succesful'
                    'making money'
                    'being funny'
                    'finding a job'
                    'writing books'
                    'making websites'
                    'playing chess'
                    'magic tricks'
                    'yoga'
                    'happiness'
                ])
            ])
            choose([
                ''
                choose([
                    'The'
                    choose([
                        'The amazing'
                        'The ridiculous'
                        'The heart-warming'
                        'The retarded'
                        'The downright retarded'
                        'The stupid'
                        'The simply stupid'
                        'The insulting'
                        'The repulsive'
                        'The revolting'
                        'The delightful'
                        'The distracting'
                        'The flabbergasting'
                        'The mind-numbing'
                        'The silly'
                        'The clever'
                        'The boring'
                        'The idiotic'
                        'The hilarious'
                        'The endless'
                        'The illustrated'
                    ])
                ]) + ' ' + choose([
                    'adventure'
                    'adventures'
                    'tale'
                    'tales'
                    'story'
                    'stories'
                    'happenings'
                    'stumblings'
                    'discoveries'
                ]) + ' of '
            ]) + choose([
                weightedChoose([
                    'James'
                    'John'
                    'Robert'
                    'Michael'
                    'William'
                    'David'
                    'Richard'
                    'Charles'
                    'Joseph'
                    'Thomas'
                    'Christopher'
                    'Daniel'
                    'Paul'
                    'Mark'
                    'Donald'
                    'George'
                    'Kenneth'
                    'Steven'
                    'Edward'
                    'Brian'
                    'Ronald'
                    'Anthony'
                    'Kevin'
                    'Jason'
                    'Jeff'
                    'Jack'
                ], 1.5)
                choose([
                    'A'
                    'Ana'
                    'Ba'
                    'Bo'
                    'Bra'
                    'Bro'
                    'Bee'
                    'Bea'
                    'Bre'
                    'Bi'
                    'Ca'
                    'Cla'
                    'Co'
                    'Da'
                    'Dee'
                    'Dri'
                    'E'
                    'Fa'
                    'Fi'
                    'Fo'
                    'Fro'
                    'Go'
                    'Ga'
                    'Gri'
                    'Gi'
                    'Gnu'
                    'Ha'
                    'Ho'
                    'I'
                    'Jo'
                    'Ja'
                    'Je'
                    'Kla'
                    'Ko'
                    'Klo'
                    'Lo'
                    'Lee'
                    'Mi'
                    'Ma'
                    'Mu'
                    'Ni'
                    'Nee'
                    'O'
                    'Oo'
                    'Pi'
                    'Pa'
                    'Po'
                    'Qua'
                    'Quo'
                    'Quee'
                    'Ri'
                    'Ra'
                    'Ro'
                    'Sti'
                    'Sla'
                    'Shwa'
                    'Shwo'
                    'To'
                    'Tra'
                    'U'
                    'Vo'
                    'Vro'
                    'Wo'
                    'Wee'
                    'Wi'
                    'Xi'
                    'Y'
                    'Zi'
                    'Zo'
                    'Za'
                ]) + choose([
                    'bble'
                    'rble'
                    'pple'
                    'ttle'
                    'ffle'
                    'stle'
                    'ffin'
                    'ggin'
                    'ggle'
                    'rgle'
                    'rbus'
                    'rtus'
                    'bus'
                    'tus'
                    'gus'
                    'rtus'
                    'rtos'
                    'zzle'
                ])
            ]) + choose([
                ' the'
                ', the ' + choose([
                    'amazing'
                    'stupid'
                    'boring'
                    'diminutive'
                    'giant'
                    'friendly'
                    'psychotic'
                    'crafty'
                    'swift'
                    'cowardly'
                    'mighty'
                    'hilarious'
                    'magic'
                    'midget'
                    'tiny'
                    'clumsy'
                    'lazy'
                    'fancy'
                    'nasty'
                    'naughty'
                    'hairy'
                    'bald'
                    'disgusting'
                    'smelly'
                    'failed'
                    'noble'
                ])
            ]) + ' ' + choose([
                'bard'
                'poet'
                'prince'
                'knight'
                'wizard'
                'sorcerer'
                'tourist'
                'shopkeeper'
                'joker'
                'blacksmith'
                'butcher'
                'gardener'
                'magician'
                'mage'
                'astronomer'
                'alchemist'
                'merchant'
                'pirate'
                'ninja'
                'shoemaker'
                'monk'
            ]) + choose([
                ''
                ''
                ''
                ''
                ''
                ' ' + choose([ 'from space' ])
            ])
            choose([
                'A shocking'
                'An amazing'
                'A vibrant'
                'A heart-warming'
                'A true'
                'An astounding'
                'A riveting'
                'A twisted'
                'A short'
                'An elaborate'
                'An overly elaborate'
                'A ridiculous'
                'A hilarious'
                'A boring'
                'An illustrated'
                'A mind-numbing'
                'A'
            ]) + ' ' + choose([
                'story'
                'tale'
                'essay'
                'book'
            ]) + ' ' + choose([
                'involving'
                'about'
                'on the subject of'
            ]) + ' ' + choose([
                'pirates'
                'ninjas'
                'dinosaurs'
                'unicorns'
                'robots'
                'cyborgs'
                'scientists'
                'superheroes'
                'maths'
            ]) + ', ' + choose([
                'surgeons'
                'penguins'
                'dolphins'
                'cheese'
                'dragons'
                'ghosts'
                'kittens'
                'sarcasm'
                'astronomers'
                'banana peels'
            ]) + ' and ' + choose([
                'spaceships'
                'vegetarians'
                'babies'
                'art'
                'time travel'
                'abortions'
                'philosophy'
                'computers'
                'punctuation'
                'magnets'
                'geometry'
                'language'
            ])
            choose([
                ''
                ''
                choose([
                    'Meet'
                    'Hey, it\'s'
                    'The life of'
                    'My life as'
                    'The day I woke up as'
                    'My life with'
                    'Living with'
                    'My friend'
                    'Me and my friend'
                    'My buddy'
                    'Me and my buddy'
                    'My neighbor'
                ]) + ' '
                choose([
                    'The'
                    choose([
                        'The amazing'
                        'The ridiculous'
                        'The heart-warming'
                        'The retarded'
                        'The downright retarded'
                        'The stupid'
                        'The simply stupid'
                        'The insulting'
                        'The repulsive'
                        'The revolting'
                        'The delightful'
                        'The distracting'
                        'The flabbergasting'
                        'The mind-numbing'
                        'The silly'
                        'The clever'
                        'The boring'
                        'The idiotic'
                        'The hilarious'
                        'The endless'
                        'The illustrated'
                    ])
                ]) + ' ' + choose([
                    'adventure'
                    'adventures'
                    'tale'
                    'tales'
                    'story'
                    'stories'
                    'happenings'
                    'stumblings'
                    'discoveries'
                ]) + ' of '
            ]) + choose([
                weightedChoose([
                    'James'
                    'John'
                    'Robert'
                    'Michael'
                    'William'
                    'David'
                    'Richard'
                    'Charles'
                    'Joseph'
                    'Thomas'
                    'Christopher'
                    'Daniel'
                    'Paul'
                    'Mark'
                    'Donald'
                    'George'
                    'Kenneth'
                    'Steven'
                    'Edward'
                    'Brian'
                    'Ronald'
                    'Anthony'
                    'Kevin'
                    'Jason'
                    'Jeff'
                    'Jack'
                ], 1.5)
                weightedChoose([
                    'Mary'
                    'Patricia'
                    'Linda'
                    'Barbara'
                    'Elizabeth'
                    'Jennifer'
                    'Maria'
                    'Susan'
                    'Margaret'
                    'Dorothy'
                    'Lisa'
                    'Nancy'
                    'Karen'
                    'Betty'
                    'Helen'
                    'Sandra'
                    'Donna'
                    'Carol'
                    'Ruth'
                    'Sharon'
                    'Michelle'
                    'Laura'
                    'Sarah'
                    'Kimberly'
                    'Deborah'
                ], 1.5)
            ]) + ', the ' + choose([
                'weird'
                'mutant'
                'normal'
                'serious'
                'confused'
                'lost'
                'exploding'
                'obese'
                'skinny'
                'whiny'
                'stupid'
                'slimy'
                'tiny'
                'giant'
                'ancient'
                'obnoxious'
                'invisible'
                'boring'
                'annoying'
                'space'
                'hairy'
                'bald'
                'ridiculous'
                'imaginary'
                'awkward'
                'stubborn'
                'pretentious'
                'naughty'
                'nasty'
                'lazy'
                'fancy'
                'magic'
                'clumsy'
                'smelly'
                'bearded'
                'lonely'
                'sleazy'
                'rabid'
                'translucent'
                'edible'
                'inedible'
                'foreign'
                'snotty'
                'mind-reading'
                'telepathic'
                'silent'
            ]) + ' ' + choose([
                'shrimp'
                'bird'
                'person'
                'chap'
                'whale'
                'deity'
                'cactus'
                'fungus'
                'alligator'
                'jellyfish'
                'crab'
                'hobo'
                'machine'
                'robot'
                'goat'
                'cyborg'
                'ninja'
                'fish'
                'mushroom'
                'spider'
                'pervert'
                'mermaid'
                'squid'
                'lamprey'
                'turtle'
                'unicorn'
                'barbarian'
                'vampire'
                'werewolf'
                'teenager'
                'baby'
                'kid'
                'lady'
                'superhero'
                'insect'
                'centaur'
                'shopkeeper'
                'caveman'
                'school teacher'
                'cosmonaut'
                'scientist'
                'doctor'
                'car salesman'
                'baker'
                'butcher'
                'cop'
                'minister'
            ])
        ])
        if randint(0, 10) == 0
            str += ', ' + choose([
                'Part'
                'Tome'
                'Volume'
            ]) + ' ' + choose([
                'I'
                'II'
                'III'
                'IV'
                'V'
                'VI'
                'VII'
                'VIII'
                'IX'
                'X'
            ])

        return str

    char: -> # {{{1
        str = "aaaabbccddeeeeffgghhhiijkkllmmnnooppqqrrrssstttuuvwwxyz.,;!?:()-'"

        if randint(0, 20) == 0
            str += '0123456789*$/#&'

        str = str.split('')
        str = choose(str)

        if randint(0, 30) == 0
            str = str.toUpperCase()

        return str

    monument: -> # {{{1
